### ISSUE TITLE
Weird edge bug on menu

### ISSUE THREAD

**Issue by angelcalvasp** [creativetimofficial/ct-material-dashboard-pro#163]
Ok so this happens from time to time and Im not sure why it happens, I thought it had to do with my project or something I had done, so I opened the good ol 2.0.1 sample project and got It to happen too

![image](https://user-images.githubusercontent.com/7502746/41430575-fbda31dc-6fd5-11e8-818e-f99e65751494.png)

As you see all the menu items from pages have an insane height

Steps to reproduce;
1.- Open Edge
2.- Open directly examples/forms/regular.html
3.- then uncollapse pages section

weirdest thing is that if I go to a page lets say extended forms and then go back to regular forms

![image](https://user-images.githubusercontent.com/7502746/41430713-66bc5c6e-6fd6-11e8-839f-b73b04aa4be7.png)

everything is ok

**Comment by groovemen** [comment]
Hello @angelcalvasp, thank you for using our products, we have released yesterday the update (v.2.0.2) in which this issue doesn't exist.
Best, 
Stefan

**Comment by angelcalvasp** [comment]
![image](https://user-images.githubusercontent.com/7502746/42186229-6fb15114-7e11-11e8-975f-20ebcfe0a2ab.png)
opened v 2.0.2 issue still exists
